### PR TITLE
chore: updating the example skills

### PR DESCRIPTION
**Pull request by abhjroy**
* **Please check if the PR fulfills these requirements**
- [Y] The commit message describes your change
- [Y] Tests for the changes have been added if possible (for bug fixes / features)
- [Y] Docs have been added / updated (for bug fixes / features)
- [Y] Changes are mentioned in the changelog (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Fixed the example skills

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their setup due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by hoegertn** [comment]
Can you please elaborate what you fixed in this PR?

**Comment by abhjroy** [comment]
in the example skill the imports were from `lib` folder which i changed to `src`. 
e.g. 
`import { AlexaTest, AplUserEventRequestBuilder, LaunchRequestBuilder, SkillSettings } from '../../lib';` --> `import { AlexaTest, AplUserEventRequestBuilder, LaunchRequestBuilder, SkillSettings } from '../../src';`

Also changed the tests, the test functions should be written inside the `it` function instead of `describe` function.
e.g.
```
describe('Hello World Skill', () => {
    // tests the behavior of the skill's LaunchRequest
    describe('LaunchRequest', () => {
        alexaTest.test([
            {
                request: new LaunchRequestBuilder(skillSettings).build(),
                says: 'Welcome to the Alexa Skills Kit, you can say hello!',
                repromptsNothing: true,
                shouldEndSession: true,
            },
        ]);
    });
```
    change to 
```
    describe('Hello World Skill', () => {
    // tests the behavior of the skill's LaunchRequest
    it('LaunchRequest', () => {
        alexaTest.test([
            {
                request: new LaunchRequestBuilder(skillSettings).build(),
                says: 'Welcome to the Alexa Skills Kit, you can say hello!',
                repromptsNothing: true,
                shouldEndSession: true,
            },
        ]);
    });
```

**Comment by hoegertn** [comment]
I am fine with running it from src if this works without problems.
The second change is not needed as the implementation of alexaTest.test creates the `it` block and these should no be nested. So describe is indeed correct here.

**Comment by abhjroy** [comment]
okay, I'll modify the changes and raise another pr

**Comment by abhjroy** [comment]
I have done the changes

**Pull request merged**
